"""Standalone localhost service. Deliberately imports no hardware API routers."""
from pathlib import Path
from typing import Literal
import os
import secrets
import subprocess
import time
from fastapi import FastAPI, HTTPException, Request
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, ConfigDict
from .defaults import bundle
from .demos import demos, get_demo, _ordinary_motion_metadata, _with_motion
import copy
import yaml
from .runtime import execute
from .policy import campaign

app=FastAPI(title='CubOS Color Twin — simulation only')

# Recordings are intentionally kept in one local, generated-artifact folder.
# The environment override is useful for review exports; filenames are always
# generated by this service and never taken from the multipart request.
RECORDINGS_DIR = Path(os.environ.get(
    'CUBOS_SIM_RECORDINGS_DIR',
    Path(__file__).resolve().parents[1] / '.local' / 'recordings',
)).expanduser().resolve()
RECORDINGS_DIR.mkdir(parents=True, exist_ok=True)
MAX_RECORDING_BYTES = 80 * 1024 * 1024
FFMPEG_TIMEOUT_SECONDS = 180


def _recording_stem() -> str:
    return f"color-twin-{time.strftime('%Y%m%d-%H%M%S', time.gmtime())}-{secrets.token_hex(5)}"


def _run_ffmpeg(args: list[str]) -> None:
    try:
        result = subprocess.run(
            ['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', *args],
            check=False,
            capture_output=True,
            timeout=FFMPEG_TIMEOUT_SECONDS,
        )
    except FileNotFoundError as exc:
        raise HTTPException(503, detail='ffmpeg is required for local recording export') from exc
    except subprocess.TimeoutExpired as exc:
        raise HTTPException(504, detail='Recording export timed out') from exc
    if result.returncode:
        detail = result.stderr.decode('utf-8', errors='replace').strip()[-1000:]
        raise HTTPException(422, detail=f'ffmpeg could not export recording: {detail}')

class YamlInput(BaseModel):
    model_config=ConfigDict(extra='forbid')
    gantry_yaml: str=Field(max_length=200000)
    deck_yaml: str=Field(max_length=200000)
    protocol_yaml: str=Field(default='',max_length=200000)
    routing: dict = Field(default_factory=dict)
    initial_position: list[float] | None = Field(default=None, min_length=3, max_length=3)

class Policy(BaseModel):
    model_config=ConfigDict(extra='forbid')
    target: str=Field(default='#b77762',pattern=r'^#[0-9a-fA-F]{6}$')
    trials: int=Field(default=8,ge=1,le=96)
    initial: int=Field(default=4,ge=1,le=12)
    total: Literal[300]=300
    acquisition: Literal['ei','lcb','random']='ei'
    exploration: float=Field(default=.05,ge=0,le=1,allow_inf_nan=False)
    seed: int=Field(default=7,ge=0,le=1000000)

class CampaignInput(YamlInput):
    policy: Policy=Field(default_factory=Policy)

@app.get('/api/twin/defaults')
def defaults(profile: str = ''):
    if profile == 'side-exit':
        # Preserve the imported prerequisite URL for existing users/tests;
        # the named three-demo catalog uses ``saved-side-exit``.
        from .side_exit import bundle as side_bundle
        return {**side_bundle(), 'id': 'side-exit-legacy', 'name': 'Legacy side-exit prerequisite', 'mode': 'side-exit'}
    return get_demo(profile).bundle()

@app.get('/api/twin/demos')
def demo_catalog():
    return {'demos': demos()}

@app.get('/api/twin/compare/ordinary')
def compare_ordinary():
    """Run the same ordinary native protocol with planning disabled/enabled."""
    demo = get_demo('ordinary-transfer')
    raw = yaml.safe_load(demo.deck_yaml)
    legacy = copy.deepcopy(raw)
    legacy.pop('motion_planning', None)
    for entry in legacy.get('labware', {}).values():
        if isinstance(entry, dict):
            entry.pop('motion', None)
            entry.pop('occupied_tip_radius_mm', None)
    legacy_run = execute(demo.gantry_yaml, yaml.safe_dump(legacy, sort_keys=False), demo.protocol_yaml, routing={'planner_enabled': False}, initial_position=demo.initial_position)
    planned_deck = yaml.safe_dump(_with_motion(yaml.safe_load(demo.deck_yaml), _ordinary_motion_metadata()), sort_keys=False)
    legacy_result = legacy_run['fluids'].get('plate.A1', {})
    planned_run = execute(demo.gantry_yaml, planned_deck, demo.protocol_yaml, routing={**demo.routing, 'planner_enabled': True}, initial_position=demo.initial_position)
    planned_result = planned_run['fluids'].get('plate.A1', {})
    legacy_inputs = {
        'gantry_yaml': demo.gantry_yaml,
        'deck_yaml': yaml.safe_dump(legacy, sort_keys=False),
        'protocol_yaml': demo.protocol_yaml,
        'initial_position': demo.initial_position,
    }
    planned_inputs = {
        'gantry_yaml': demo.gantry_yaml,
        'deck_yaml': planned_deck,
        'protocol_yaml': demo.protocol_yaml,
        'initial_position': demo.initial_position,
    }
    return {'legacy': legacy_result, 'planned': planned_result,
            'same_liquid_outcome': legacy_result == planned_result,
            'legacy_route': legacy_run.get('route'), 'planned_route': planned_run.get('route'),
            'legacy_run': legacy_run, 'planned_run': planned_run,
            'legacy_inputs': legacy_inputs, 'planned_inputs': planned_inputs}

@app.post('/api/twin/simulate')
def simulate(body: YamlInput):
    try: return execute(body.gantry_yaml,body.deck_yaml,body.protocol_yaml,routing=body.routing or None,initial_position=body.initial_position)
    except Exception as exc:
        raise HTTPException(422,detail=f'{type(exc).__name__}: {exc}') from exc

@app.post('/api/twin/campaign')
def optimize(body: CampaignInput):
    try: return campaign(body.gantry_yaml,body.deck_yaml,body.policy)
    except Exception as exc:
        raise HTTPException(422,detail=f'{type(exc).__name__}: {exc}') from exc

@app.post('/api/twin/recording')
async def export_recording(request: Request):
    """Convert a browser WebM canvas capture into reviewable GIF and MP4 files."""
    content_length = request.headers.get('content-length')
    if content_length:
        try:
            if int(content_length) > MAX_RECORDING_BYTES + 1024 * 1024:
                raise HTTPException(413, detail='Recording upload is limited to 80 MB')
        except ValueError as exc:
            raise HTTPException(400, detail='Invalid upload content length') from exc
    content_type = request.headers.get('content-type', '').split(';', 1)[0].strip().lower()
    if content_type and content_type not in {'video/webm', 'application/octet-stream'}:
        raise HTTPException(415, detail='Recording must be a WebM video')

    stem = _recording_stem()
    source = RECORDINGS_DIR / f'{stem}.webm'
    gif = RECORDINGS_DIR / f'{stem}.gif'
    mp4 = RECORDINGS_DIR / f'{stem}.mp4'
    written = 0
    try:
        with source.open('wb') as output:
            async for chunk in request.stream():
                if not chunk:
                    continue
                written += len(chunk)
                if written > MAX_RECORDING_BYTES:
                    raise HTTPException(413, detail='Recording upload is limited to 80 MB')
                output.write(chunk)
        if written == 0:
            raise HTTPException(422, detail='Recording upload is empty')

        # GIF 720 px 10 fps 160-color palette; MP4 960 px 12 fps H.264
        _run_ffmpeg([
            '-i', str(source),
            '-vf', 'scale=720:-2:flags=lanczos,fps=10,split[s0][s1];[s0]palettegen=stats_mode=full:max_colors=160[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle',
            '-loop', '0',
            str(gif),
        ])
        _run_ffmpeg([
            '-i', str(source),
            '-vf', 'scale=960:-2:flags=lanczos,fps=12',
            '-an', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-crf', '18',
            '-movflags', '+faststart',
            str(mp4),
        ])
    except HTTPException:
        gif.unlink(missing_ok=True)
        mp4.unlink(missing_ok=True)
        raise
    except Exception:
        gif.unlink(missing_ok=True)
        mp4.unlink(missing_ok=True)
        raise
    finally:
        source.unlink(missing_ok=True)
    return {
        'id': stem,
        'gif_url': f'/api/twin/recordings/{gif.name}',
        'mp4_url': f'/api/twin/recordings/{mp4.name}',
        'gif_filename': gif.name,
        'mp4_filename': mp4.name,
    }

if RECORDINGS_DIR.is_dir(): app.mount('/api/twin/recordings', StaticFiles(directory=RECORDINGS_DIR), name='recordings')

DIST=Path(__file__).resolve().parents[1]/'dist'
if DIST.is_dir(): app.mount('/',StaticFiles(directory=DIST,html=True),name='ui')
