serial_port: /dev/ttyUSB0
gantry_type: cub_xl
cnc:
  factory_z_travel_mm: 117.0
  y_axis_motion: head
  safe_z: 100.0
working_volume:
  x_min: 0.0
  x_max: 386.0
  y_min: 0.0
  y_max: 250.0
  z_min: 0.0
  z_max: 100.0
origin_policy: home_origin
grbl_settings:
  dir_invert_mask: 1
  status_report: 0
  homing_enable: true
  homing_dir_mask: 0
  steps_per_mm_x: 400.0
  steps_per_mm_y: 400.0
  steps_per_mm_z: 400.0
  max_travel_x: 401.0
  max_travel_y: 301.0
  max_travel_z: 85.0
instruments:
  potentiostat:
    type: potentiostat
    vendor: admiral
    offset_x: -56.7
    offset_y: 3.8
    depth: 100.0
    port: ''
    channel: 0
    offline: true
  camera:
    type: camera
    vendor: mount_only
    offset_x: 0.0
    offset_y: 0.0
    depth: 0.0
    offline: true
  vial_capper_decapper:
    type: mounted_tool
    vendor: mount_only
    offset_x: 62.9
    offset_y: 5.1
    depth: 61.5
    offline: true
