import React, {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import Scene from './Scene'
import {stateAt,type Bundle,type Run,type Policy} from './types'
import './style.css'

async function api(path:string,body?:unknown){const response=await fetch(`/api/twin/${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data}
function save(name:string,text:string,type='text/yaml'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const defaultPolicy:Policy={target:'#b77762',trials:8,initial:4,total:300,acquisition:'ei',exploration:.05,seed:7}
function App(){
 const [bundle,setBundle]=useState<Bundle|null>(null),[run,setRun]=useState<Run|null>(null),[policy,setPolicy]=useState(defaultPolicy)
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(24),[busy,setBusy]=useState(true),[error,setError]=useState('')
 const [view,setView]=useState('orbit'),[tab,setTab]=useState('experiment'),[editor,setEditor]=useState<'protocol_yaml'|'gantry_yaml'|'deck_yaml'>('protocol_yaml'),[showAssumptions,setShowAssumptions]=useState(false),[selectedWell,setSelectedWell]=useState('A1')
 const [lastPolicy,setLastPolicy]=useState<Policy|null>(null);const [runInputs,setRunInputs]=useState<Pick<Bundle,'gantry_yaml'|'deck_yaml'|'protocol_yaml'>|null>(null)
 const sideExit=!!run?.deck_metadata?.tips.side_exit
 const exitDirection=(run?.deck_metadata?.tips.side_exit?.exit_x??0)<(run?.points.tips?.[0]?.x??0)?'−X':'+X'
 const pickupMoves=run?.events.filter(e=>e.kind==='move'&&e.command==='pick_up_tip'&&e.step===0)??[]
 const upload=useRef<HTMLInputElement>(null)
 useEffect(()=>{let active=true;api(new URLSearchParams(location.search).get('profile')==='side-exit'?'defaults?profile=side-exit':'defaults').then(async b=>{const r=await api('simulate',{gantry_yaml:b.gantry_yaml,deck_yaml:b.deck_yaml,protocol_yaml:b.protocol_yaml});if(active){setBundle(b);setRun(r);setRunInputs({gantry_yaml:b.gantry_yaml,deck_yaml:b.deck_yaml,protocol_yaml:b.protocol_yaml})}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[])
 useEffect(()=>{if(!playing||!run)return;let frame=0,last=performance.now();function tick(now:number){const dt=(now-last)/1000;last=now;setTime(t=>Math.min(run!.duration,t+dt*speed));frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing,run,speed])
 useEffect(()=>{if(run&&time>=run.duration-.02)setPlaying(false)},[time,run])
 const state=stateAt(run,time);const history=run?.history??[];const completed=history.filter(h=>run?.events.some(e=>e.kind==='capture'&&e.target===`plate.${h.well}`&&e.t<=time));const best=completed.length?completed.reduce((a,b)=>a.loss<b.loss?a:b):null;const currentTrial=history.find(h=>h.well===state.capture?.target?.split('.')[1]);const selected=state.wells[`plate.${selectedWell}`];const percent=run?100*time/run.duration:0
 async function submit(campaign:boolean){if(!bundle)return;setBusy(true);setError('');setPlaying(false);try{const body={gantry_yaml:bundle.gantry_yaml,deck_yaml:bundle.deck_yaml,protocol_yaml:bundle.protocol_yaml};const result:Run=await api(campaign?'campaign':'simulate',campaign?{...body,policy}:body);setRun(result);setRunInputs({...body,protocol_yaml:result.protocol_yaml??body.protocol_yaml});setTime(0);setPlaying(true);setLastPolicy(campaign?{...policy}:null);if(result.protocol_yaml)setBundle({...bundle,protocol_yaml:result.protocol_yaml})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function change<K extends keyof Policy>(key:K,value:Policy[K]){setPolicy(p=>({...p,[key]:value}))}
 return <main className="app">
 <header className="topbar"><div className="brand"><span className="logo">c<span>◦</span></span><b>CubOS</b><span className="slash">/</span><span>Color Lab</span><span className="version">01</span></div><div className="topright"><span className="badge"><i/> SIMULATION ONLY</span><button className="quiet" onClick={()=>setShowAssumptions(!showAssumptions)}>Model notes ↗</button></div></header>
 <div className="workspace-heading"><div><div className="eyebrow">VIRTUAL EXPERIMENT WORKSPACE</div><h1>A little color. A smarter next step.</h1><p>{sideExit?`1000 µL · 70 mm tips · lift 30 mm, then exit ${exitDirection}`:'Genmitsu PROVer V2 · Picus 2 / 120 µL · Arducam'}</p></div><button className="primary" disabled={busy||!bundle} onClick={()=>submit(true)}>{busy?'Preparing simulation…':'↗  Run BO campaign'}</button></div>
 <nav className="tabs"><div><button className={tab==='experiment'?'active':''} onClick={()=>setTab('experiment')}>Experiment</button><button className={tab==='yaml'?'active':''} onClick={()=>setTab('yaml')}>Protocol & setup <span>YAML</span></button></div><span className="estimate">{sideExit?'◌ Side-exit demo · 56 mm Z travel · uncalibrated':'◌ Photo model · Z envelope 100 mm, unverified'}</span></nav>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 <div className="layout">
 <aside className="policy panel"><div className="panel-label">01 / EXPERIMENT DESIGN</div><h2>Find your color</h2><p className="muted">A closed loop from recipe to observation.</p>
 <label className="field-title" htmlFor="target">Target color</label><div className="target-card"><input aria-label="Target color" id="target" type="color" value={policy.target} onChange={e=>change('target',e.target.value)}/><div><b>{policy.target.toUpperCase()}</b><small>Synthetic camera RGB</small></div><span>✳</span></div>
 <label className="field-title" htmlFor="acquisition">Acquisition policy</label><select id="acquisition" value={policy.acquisition} onChange={e=>change('acquisition',e.target.value)}><option value="ei">Expected improvement</option><option value="lcb">Lower confidence bound</option><option value="random">Random baseline</option></select><p className="help">Gaussian process · three-color mixture space</p>
 <div className="fields"><label>Trial budget<input aria-label="Trial budget" type="number" min="1" max="96" value={policy.trials} onChange={e=>change('trials',+e.target.value)}/></label><label>Initial samples<input aria-label="Initial samples" type="number" min="1" max="12" value={policy.initial} onChange={e=>change('initial',+e.target.value)}/></label><label>Total / µL<input aria-label="Total volume" type="number" value={300} readOnly/></label><label>Random seed<input aria-label="Random seed" type="number" min="0" max="1000000" value={policy.seed} onChange={e=>change('seed',+e.target.value)}/></label></div>
 <label className="range-label">Exploration <b>{policy.exploration.toFixed(2)}</b><input aria-label="Exploration" type="range" min="0" max="1" step=".01" value={policy.exploration} onChange={e=>change('exploration',+e.target.value)}/></label>
 <div className="divider"/><div className="panel-label">SOURCE VIALS <span>3 × 4 mL</span></div><div className="stocks">{bundle?.stocks.map(s=><div key={s.name}><i style={{background:s.hex}}/><span>{s.name}</span><small>{s.target.split('.')[1]}</small></div>)}</div>
 <p className="help">50–200 µL per color · exactly 300 µL per well. No diluent. Capacity: {sideExit?'1000':'120'} µL per stroke. Runs stop before tips or stock run out.</p>
 <div className="loop-note"><span>↻</span><div><b>Learn from each trial</b><p>Propose → pipette → observe → update</p></div></div>
 </aside>
 <section className="center panel">
 {tab==='experiment'?<><div className="scene-heading"><div><span className="status-dot"/> <b>{busy?'Preparing':playing?'Running simulation':time>= (run?.duration??Infinity)-.02?'Run complete':'Digital twin ready'}</b><small>{state.current?.command.replaceAll('_',' ')??'Native CubOS protocol runtime'}</small></div><div className="view-buttons">{(sideExit?['orbit','front','top','rack']:['orbit','front','top']).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='orbit'?'3D':v==='rack'?'Rack close-up':v[0].toUpperCase()+v.slice(1)}</button>)}</div></div>
 <div className="scene-wrap"><Scene run={run} time={time} view={view}/><div className="scene-label"><span>GENMITSU 3018</span><small>Moving bed / Y · moving head / X, Z</small></div><div className="axes"><span style={{color:'#e18c7e'}}>X →</span><span style={{color:'#9fd4ac'}}>Y ↗</span><span style={{color:'#8dc8e3'}}>Z ↑</span></div><div className="coordinate-bar">{['X','Y','Z'].map((a,i)=><span key={a}>{a} <b>{state.pose[i].toFixed(1)}</b></span>)}<small>mm · deck frame</small></div><div className="orbit-hint">Drag to orbit · scroll to zoom</div></div>
 <div className="transport"><button className="play" aria-label={playing?'Pause playback':'Play playback'} disabled={!run||busy} onClick={()=>{if(time>=run!.duration-.02)setTime(0);setPlaying(!playing)}}>{playing?'Ⅱ':'▶'}</button><button className="reset" aria-label="Restart playback" onClick={()=>{setTime(0);setPlaying(false)}}>↺</button><input aria-label="Simulation timeline" type="range" min="0" max={run?.duration??1} step=".01" value={time} onChange={e=>{setPlaying(false);setTime(+e.target.value)}}/><span>{Math.floor(time/60)}:{Math.floor(time%60).toString().padStart(2,'0')}</span><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[1,8,24,64].map(v=><option key={v} value={v}>{v}×</option>)}</select></div>
 {sideExit&&<div className="yaml-actions"><button onClick={()=>{const e=pickupMoves.at(-2);if(e){setTime(e.t);setSpeed(1);setPlaying(true)}}}>▶ Review first pickup at 1×</button><button onClick={()=>{const e=pickupMoves.at(-2);if(e){setTime(e.t+e.duration);setPlaying(false)}}}>A · Lifted 30 mm</button><button onClick={()=>{const e=pickupMoves.at(-1);if(e){setTime(e.t+e.duration);setPlaying(false)}}}>B · Exited {exitDirection}</button></div>}
 <div className="scene-foot"><span>ESTIMATED GEOMETRY</span><span>Native YAML → CubOS commands → virtual instruments</span><b>{Math.round(percent)}%</b></div></>:<div className="yaml-pane"><div className="yaml-toolbar">{(['protocol_yaml','gantry_yaml','deck_yaml']as const).map(k=><button className={editor===k?'active':''} key={k} onClick={()=>setEditor(k)}>{k.replace('_yaml','')}.yaml</button>)}</div><div className="yaml-info">Simulation inputs · edits are validated by CubOS before playback.</div><textarea aria-label="YAML editor" spellCheck={false} value={bundle?.[editor]??''} onChange={e=>bundle&&setBundle({...bundle,[editor]:e.target.value})}/><div className="yaml-actions"><input ref={upload} type="file" accept=".yaml,.yml" hidden onChange={async e=>{const f=e.target.files?.[0];if(f&&bundle)setBundle({...bundle,[editor]:await f.text()});e.target.value=''}}/><button onClick={()=>upload.current?.click()}>Import YAML</button><button onClick={()=>bundle&&save(editor.replace('_yaml','.yaml'),bundle[editor])}>Download</button><button className="primary" disabled={busy} onClick={()=>submit(false)}>Validate & simulate</button></div></div>}
 </section>
 <aside className="results panel"><div className="panel-label">02 / OBSERVATION</div><h2>The feedback loop</h2><div className="camera-label"><span className="status-dot"/> VIRTUAL ARDUCAM <small>RGB</small></div><div className="camera-preview"><div className="crosshair h"/><div className="crosshair v"/><div className="sample" style={{background:state.capture?.color??'#d0d9d3'}}/><span className="camera-corner tl"/><span className="camera-corner tr"/><span className="camera-corner bl"/><span className="camera-corner br"/><small>{state.capture?.target??'Awaiting capture'}</small></div><p className="help">Synthetic color swatch · optics not calibrated</p>{lastPolicy&&<p className="help">Run target: {lastPolicy.target.toUpperCase()} · seed {lastPolicy.seed}</p>}
 <div className="readout"><div><small>BEST RGB DISTANCE ↓</small><strong>{best?best.loss.toFixed(2):'—'}</strong></div><div className="best-color" style={{background:best?.color??'#28373d'}}/></div><div className="progress-meta"><span>{completed.length} / {run?.requested_trials??(history.length||'—')} trials observed</span><span>{best?`Best: ${best.well}`:'Ready to learn'}</span></div>
 {run?.stop_reason&&<p className="help">Planned stop after {history.length} trials: {run.stop_reason}</p>}<div className="chart"><svg viewBox="0 0 240 92" role="img" aria-label="Best observed RGB distance by trial"><path d="M0 20H240 M0 50H240 M0 80H240" stroke="#2b3b42" strokeDasharray="3 5"/>{completed.length>0&&<polyline points={completed.map((h,i)=>`${12+i*216/Math.max(1,history.length-1)},${80-Math.min(...completed.slice(0,i+1).map(x=>x.loss))/100*65}`).join(' ')} fill="none" stroke="#f1b46d" strokeWidth="2.5"/>}{completed.map((h,i)=><circle key={h.trial} cx={12+i*216/Math.max(1,history.length-1)} cy={80-Math.min(...completed.slice(0,i+1).map(x=>x.loss))/100*65} r="3" fill="#f1b46d"/>)}</svg><div><span>TRIAL 1</span><span>LOWER IS CLOSER</span></div></div>
 <div className="divider"/><div className="panel-label">LATEST RECIPE <span>{currentTrial?.well??'—'}</span></div><div className="recipe">{bundle?.stocks.map((s,i)=><div key={s.name}><span><i style={{background:s.hex}}/>{s.name}</span><b>{currentTrial?currentTrial.volumes[i]:'—'} <small>µL</small></b></div>)}</div>
 <button className="export" disabled={!run} onClick={()=>save('color-twin-run.json',JSON.stringify({policy:lastPolicy,assumptions:bundle?.assumptions,...runInputs,run},null,2),'application/json')}>↓ Export run & observations</button>
 </aside>
 </div>
 <section className="bottom-grid"><div className="plate-panel panel"><div className="panel-label">03 / EXPERIMENT PLATE <span>96 WELLS</span></div><div className="plate-body"><div className="well-grid"><span/>{Array.from({length:12},(_,i)=><small key={i}>{i+1}</small>)}{Array.from({length:8},(_,r)=><React.Fragment key={r}><small>{String.fromCharCode(65+r)}</small>{Array.from({length:12},(_,c)=>{const id=`${String.fromCharCode(65+r)}${c+1}`;return <button key={id} aria-label={`Well ${id}`} title={id} className={selectedWell===id?'selected':''} style={{background:state.wells[`plate.${id}`]?.color??'#26363d'}} onClick={()=>setSelectedWell(id)}/>})}</React.Fragment>)}</div><div className="well-detail"><b>{selectedWell}</b><span>{selected?`${selected.volume.toFixed(0)} µL`:'Empty well'}</span><small>{selected?.color.toUpperCase()??'Select a well to inspect'}</small></div></div></div>
 <div className="trace-panel panel"><div className="panel-label">04 / EXECUTION TRACE <span>{run?.steps??0} STEPS</span></div><div className="trace-lines">{(run?.events.filter(e=>e.t<=time&&(e.kind==='move'||e.kind==='step'||e.kind==='capture')).slice(-4)??[]).map((e,i)=><div key={`${e.t}-${i}`}><time>{e.t.toFixed(1).padStart(6,'0')}s</time><span className={e.kind==='move'?'code':'action'}>{e.gcode??`${e.command.replaceAll('_',' ')}${e.target?' → '+e.target:''}`}</span><small>{e.kind==='move'?'derived path':'CubOS'}</small></div>)}</div><p className="help">G-code shown describes the resolved path; controller responses and acceleration are not emulated.</p></div></section>
 <footer><span>CubOS / Color Lab</span><span>Virtual hardware · reproducible policies · no machine connection</span></footer>
 {showAssumptions&&<div className="modal-backdrop" onClick={()=>setShowAssumptions(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Model assumptions" onClick={e=>e.stopPropagation()}><div className="panel-label">MODEL NOTES<button onClick={()=>setShowAssumptions(false)}>Close ×</button></div><h2>A photo-grounded first model</h2><p>The assembly and moving-bed mechanics follow your three photographs. Calibration is still required for physical accuracy.</p><ul>{bundle?.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>{sideExit?'1000':'120'} µL capacity is isolated in the simulation adapter. Production Picus model definitions are unchanged.</p><div className="notice">Next measurements: usable XYZ travel, nozzle and camera offsets, tip extension, labware anchors, camera field of view, and real color standards.</div></section></div>}
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
