"""Generate MkDocs API reference pages from the Python package tree."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import mkdocs_gen_files

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOTS = [
    REPO_ROOT / "src",
    REPO_ROOT / "data",
]
EXCLUDED_PARTS: set[str] = set()


def iter_python_modules() -> list[tuple[str, Path, Path, bool]]:
    """Return module metadata for docs generation.

    Each tuple contains:
    - dotted module path
    - repository-relative source path
    - docs output path under ``reference/``
    - whether the module is a package ``__init__``
    """
    modules: list[tuple[str, Path, Path, bool]] = []

    for root in SOURCE_ROOTS:
        if not root.exists():
            continue

        for source_path in sorted(root.rglob("*.py")):
            if "__pycache__" in source_path.parts:
                continue

            repo_relative = source_path.relative_to(REPO_ROOT)
            module_parts = list(repo_relative.with_suffix("").parts)
            if any(part in EXCLUDED_PARTS for part in module_parts):
                continue
            is_package = module_parts[-1] == "__init__"

            if is_package:
                module_parts = module_parts[:-1]
                docs_path = Path("reference", *module_parts, "index.md")
            else:
                docs_path = Path("reference", *module_parts).with_suffix(".md")

            module_name = ".".join(module_parts)
            if not module_name:
                continue

            modules.append((module_name, repo_relative, docs_path, is_package))

    return modules
modules = iter_python_modules()
package_children: dict[str, list[tuple[str, Path]]] = defaultdict(list)
top_level_modules: dict[str, list[tuple[str, Path]]] = defaultdict(list)
package_pages: dict[str, Path] = {}

for module_name, source_path, docs_path, is_package in modules:
    parts = module_name.split(".")

    if is_package:
        package_pages[module_name] = docs_path
    if len(parts) > 1:
        package_children[".".join(parts[:-1])].append((module_name, docs_path))
    top_level_modules[parts[0]].append((module_name, docs_path))

for module_name, source_path, docs_path, is_package in modules:
    # Use short name (e.g. "move" not "src.protocol_engine.commands.move")
    short_name = module_name.rsplit(".", 1)[-1]
    parts = module_name.split(".")

    lines = []

    # Add back link to parent package for non-top-level modules
    if len(parts) > 1:
        parent_name = ".".join(parts[:-1])
        parent_page = package_pages.get(parent_name)
        if parent_page is not None:
            parent_short = parent_name.rsplit(".", 1)[-1]
            # Compute relative path from this doc page's directory to parent index
            from os.path import relpath
            rel = relpath(str(parent_page), str(docs_path.parent))
            lines.append(f"[&larr; Back to {parent_short}]({rel})")
            lines.append("")

    lines.extend([
        f"# {short_name}",
        "",
        "<!-- Auto-generated by docs/gen_ref_pages.py. -->",
        "",
        f"::: {module_name}",
        "    options:",
        "      show_root_heading: false",
        "",
    ])

    children = sorted(package_children.get(module_name, []))
    if children and is_package:
        lines.extend(
            [
                "## Submodules",
                "",
            ]
        )
        for child_name, child_path in children:
            if child_name == module_name:
                continue
            link_target = child_path.name if child_path.parent == docs_path.parent else str(
                child_path.relative_to(docs_path.parent)
            )
            lines.append(f"- [{child_name}]({link_target})")
        lines.append("")

    with mkdocs_gen_files.open(docs_path, "w") as fd:
        fd.write("\n".join(lines))

    mkdocs_gen_files.set_edit_path(docs_path, source_path)

index_lines = [
    "# API Reference",
    "",
    "These pages are generated from the Python package tree during the MkDocs build.",
    "",
    "Narrative operator guidance belongs in the manual docs pages; code-level details belong here.",
    "",
]

# Group by second-level package (e.g. src.deck, src.gantry) instead of
# lumping everything under a single "src" heading.
second_level: dict[str, list[tuple[str, Path]]] = defaultdict(list)

for package_name in sorted(top_level_modules):
    entries = sorted(top_level_modules[package_name])
    for module_name, docs_path in entries:
        parts = module_name.split(".")
        if len(parts) >= 2:
            heading = ".".join(parts[:2])
        else:
            heading = parts[0]
        second_level[heading].append((module_name, docs_path))

for heading in sorted(second_level):
    # Use the short name (e.g. "gantry" not "src.gantry") for display
    display = heading.split(".")[-1] if "." in heading else heading
    index_lines.append(f"## `{display}`")
    index_lines.append("")

    pkg_index = package_pages.get(heading)
    if pkg_index is not None:
        index_lines.append(
            f"- [{heading}]({pkg_index.relative_to('reference')})"
        )

    for module_name, docs_path in second_level[heading]:
        if module_name == heading:
            continue
        index_lines.append(
            f"- [{module_name}]({docs_path.relative_to('reference')})"
        )
    index_lines.append("")

with mkdocs_gen_files.open("reference/index.md", "w") as fd:
    fd.write("\n".join(index_lines))
